OperationalError: (pymysql.err.OperationalError) (1040, u'Too many connections') (Background on this error at: http://sqlalche.me/e/e3q8)


扩大mysql 的默认连接数量


解决方式



#### 排错
```
systemctl status  -l libvirtd.service、
```

* 报错

```
9月 18 17:42:25 compute1.localdomain systemd[1]: [/usr/lib/systemd/system/libvirtd.service:36] Unknown lvalue 'TasksMax' in section 'Service'
```

* 解决：
更新系统软件包
```
yum install systemd-*
```


* 报错
 Build of instance b9d70ec1-2c2f-4c76-b7a6-c0a706695148 aborted: Volume 503d2db9-5ebc-4e70-8eda-0f2dcaf76125 did not finish being created even after we waited 187 seconds or 61 attempts. And its status is downloading.].
* 解决
从问题的现象上来看，OpenStack创建实例提示失败的具体原因如下：
Build of instance aborted: Volume did not finish being created even after we waited 191 seconds or 61 attempts. And its status is downloading.
从错误原因上推测，OpenStack在不停尝试61次后，宣告创建实例失败。此时，卷创建依然还未完成。所以，实例创建失败的原因可能为，卷创建需要的时间比较久，在卷创建成功完成之前，Nova组件等待超时了。
查看cinder日志，可以看到，在实例创建失败并等待一段时间之后，日志里有提示卷创建成功：
Volume created successfully.


在nova.conf中有一个控制卷设备重试的参数：block_device_allocate_retries，可以通过修改此参数延长等待时间。
该参数默认值为60，这个对应了之前实例创建失败消息里的61 attempts。我们可以将此参数设置的大一点，例如：180。这样Nova组件就不会等待卷创建超时，也即解决了此问题。
https://www.topomel.com/archives/720.html
